### ISSUE TITLE
Support For Laravel 10?

### ISSUE THREAD

**Issue by islamroshan** [kirkbushell/eloquence#104]
while installing into Laravel 10, it gives the error, check the error message below,
Problem 1
    - kirkbushell/eloquence[4.0.0, ..., 4.1.0] require illuminate/database ~7.0 -> found illuminate/database[v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another required.
    - Root composer.json requires kirkbushell/eloquence ~4.0 -> satisfiable by kirkbushell/eloquence[4.0.0, 4.0.1, 4.1.0].

should I downgrade the illuminate/database in the composer.json file to "7.0"?

thanks.

**Comment by Tahiaji** [comment]
https://github.com/kirkbushell/eloquence/pull/103 this one?

**Comment by fetzi** [comment]
Support for Laravel 10 is available in v10 of eloquence
