### ISSUE TITLE
`->wasChanged` doesn't work with camelCased properties.

### ISSUE THREAD

**Issue by mikebronner** [kirkbushell/eloquence#108]
Was using the `wasChanged` method the other day, and noticed it is not compatible with camelCased properties. Thought I'd mention it in case you were open to adding that functionality. :) Thanks!

**Comment by kirkbushell** [comment]
Thanks, @mikebronner . Would be really helpful if you could check out the 11.0 branch and see if it's even an issue.

**Comment by kirkbushell** [comment]
@mikebronner v11 released - please test on that branch and let me know if it works.
