### ISSUE TITLE
CamelCasing does not work on updateOrCreate method

### ISSUE THREAD

**Issue by aldrengadon** [kirkbushell/eloquence#110]
Got this error when I tried to update a table using update and updateOrCreate functions with hasOne relationship.
![image](https://github.com/kirkbushell/eloquence/assets/51815662/d3763190-5a0d-41f5-b75f-04cac9c558dd)

create and createMany functions are working fine though.

**Comment by aldrengadon** [comment]
Sorry for the confusion, CamelCasing works fine.

**Comment by aldrengadon** [comment]
Reopening this again as, **updateOrCreate** method is not working.

Got this error:
![image](https://github.com/kirkbushell/eloquence/assets/51815662/79beb6b8-f43b-4389-b872-63580fb7ac35)


create, createMany and update methods are working fine.

**Comment by kirkbushell** [comment]
@aldrengadon in that case you have to use snake_case, as it bypasses the model's configuration - you're basically working directly with database columns.
