### ISSUE TITLE
v11 dynamic relation property not working

### ISSUE THREAD

**Issue by JustinElst** [kirkbushell/eloquence#114]
Hi, Thanks for all your great work.

I have upgraded [eloquence](https://github.com/kirkbushell/eloquence) to V11 but now I get the following message:

> The attribute [relation_name] either does not exist or was not retrieved for model

I am trying to access the relation like so:
`$model->relationName->attributeValueOfRelation`
In the model I have this relationship definition:
```
class Model extends LaravelModel
{
    use HasCamelCasing;

    public function relationName(): BelongsTo
    {
        return $this->belongsTo(RelationModel::class);
    }
}
```
If I revert this commit, everything works as expected:
https://github.com/kirkbushell/eloquence/commit/15b885252a1628cbc4ba0f31015329143ab42018

What am I overlooking, the documentation/changelog doesn't mention anything about relationships or its definition...

**Comment by kirkbushell** [comment]
@JustinElst Sorry for slow response, not sure why I'm not getting notifications here.

Yeah, I see the issue - relationships aren't being picked up via snake_case.

Should be fixed now in 11.0.2
