### ISSUE TITLE
This doesn't work well with pivot tables.

### ISSUE THREAD

**Issue by brenjt** [kirkbushell/eloquence#19]
If I have a pivot table, upon attaching the database throws an error saying that the ID does not have a default value. I assume that laravel isn't using the your Model when inserting the new record.

Any thoughts?

**Comment by kirkbushell** [comment]
You'll need to show your model setup brenjt, else I can't help. I haven't seen this issue personally.

**Comment by kirkbushell** [comment]
@brenjt - if you can show the issue you're having by showing some code you're using, happy to help - otherwise I'll close this issue.
