### ISSUE TITLE
Documentation should explain that the service provider is not mandatory

### ISSUE THREAD

**Issue by leonardoalifraco** [kirkbushell/eloquence#29]
Hi Kirk,

Thanks for this awesome package.

I was looking for a way to have a consistent coding convention on my Laravel applications and I started using only the CamelCaseModel trait on a base class for all my models.

I believe that the documentation has to explain that adding the service provider does some things that the owner of the application might not want (for instance: the uuids), apart from changing the binding for the eloquent model. And, most importantly, that the user can just use the trait without registering the service provider.

If you agree, I can add the necessary changes on the readme.md and make a pull request.

**Comment by kirkbushell** [comment]
The ServiceProvider is necessary if you want camel casing to be used properly. It's necessary for things like pivot models. However, if the documentation needs to be clearer about that fact then I'm happy for a PR to be provided.
