### ISSUE TITLE
[rfc] are you sure Sluggable::getRouteKey returns right value?

### ISSUE THREAD

**Issue by constb** [kirkbushell/eloquence#38]
are you sure ``Sluggable::getRouteKey`` returns right value? its name suggests it should return field name, but you are returning ``$this->slug`` i.e. a value...

**Comment by kirkbushell** [comment]
Hmmm, tbh I'm not sure. I mean I've been using the system for at least 18 months now on our platform at work and had zero problems.

**Comment by kirkbushell** [comment]
Yup, it's correct - the base method returns an attribute value.
