### ISSUE TITLE
Adding support for Polymorphic relationships

### ISSUE THREAD

**Issue by bronxct1** [kirkbushell/eloquence#41]
I've come across this package and noticed that only basic relation types are currently supported. I'm currently working on a pull request to add support for polymorphic relationships. I should have the PR ready in the next couple of days but I wanted to see what the initial reaction would be to adding such a feature.

**Comment by kirkbushell** [comment]
That would be awesome, I'm all for that. I just haven't built it as I haven't personally needed it - seems this is the first real case for it :) I can certainly see the usefulness of it, however.

**Comment by bronxct1** [comment]
Great, I have a working version of this already. I'm going to do some cleanup and submit the PR tomorrow so we'll be able to go over the implementation.

**Comment by kirkbushell** [comment]
Awesome, thank you!

**Comment by samirgit** [comment]
is this package working for laravel 5.1? i have installed it and followed the instructions but still my models still return snake_case..

**Comment by kirkbushell** [comment]
@bronxct1 are you still interested in completing this? If not, I'll close the issue.

**Comment by bronxct1** [comment]
I am, I'm using this currently on a project but have not had a chance to work out all of the kinks. Also currently getting an error on eloquence:rebuild command that has appeared. 
```
  [PhpParser\Error]
  Syntax error, unexpected ')', expecting T_VARIABLE on line 25
```
If you want to close that will be fine and I can reopen when I have a pull request

**Comment by kirkbushell** [comment]
@bronxct1 am working toward a 2.1.0 release now - would you happen to have time for that PR?

**Comment by bronxct1** [comment]
@kirkbushell going to close this as I don't have time for the PR and I found some issues with the feature that I don't have bandwidth to fix at this time. I will re-open if I can make progress on adding this feature.
