### ISSUE TITLE
Please Fix Readme for camelCasing

### ISSUE THREAD

**Issue by samirgit** [kirkbushell/eloquence#42]
<pre>
use Eloquence\Behaviours\CamelCasing;

class SomeModel extends Model 
{
     use CamelCasing;
}
</pre>

**Comment by kirkbushell** [comment]
Sorry, what exactly is the problem? If you could write a PR that'd be a lot easier.

**Comment by kirkbushell** [comment]
Also, if you have any issues with install, please note it as a separate task (referring to your comment on another thread).
