### ISSUE TITLE
CamelCasing and firstOrNew, firstOrCreate, etc. methods

### ISSUE THREAD

**Issue by cviebrock** [kirkbushell/eloquence#43]
I'm pretty sure these methods don't work with camel-casing enabled on the model, since the array of attributes passed to each is simply passed through to the `where()` clause of a query.

I think the fix is reasonably simple: overload all these methods in the `CamelCasing` trait, snake_case all the array keys, then return the parent method.

Not sure if that's the best way to do it, though.  Thoughts?

**Comment by kirkbushell** [comment]
That's definitely the best way.

**Comment by cviebrock** [comment]
There you go. :)

**Comment by cviebrock** [comment]
Not entirely related, but this doesn't work either (if the `$data` array has camel-cased keys):

```php
$model = MyCamelCasedModel::where($data)->get();
```

I think the fix here is rather larger... :worried:

**Comment by kirkbushell** [comment]
Yeah I won't or wouldn't bother with that - that's dealing directly with the query builder then.

**Comment by kirkbushell** [comment]
CamelCase functionality was there initially just to deal with JSON responses, and it grew substantially.
