### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by cviebrock** [kirkbushell/eloquence#46]
Just wondering if you are planning a new release soon. :)

**Comment by kirkbushell** [comment]
Not at the moment, but there's lots in the pipeline with some new features and improvements. Just a bit busy right now but March looks doable. 

If there's something specific you'd like released let me know and I'll see what I can do.

**Comment by cviebrock** [comment]
I was hoping to use those artisan commands that are in the master branch.  Although I probably owe you some tests for them first ... ;)

**Comment by kirkbushell** [comment]
Yes that would be nice ;)

**Comment by kirkbushell** [comment]
Still waiting on tests @cviebrock ;)

I have a few things to work on for 2.1.0, which may even become a 3.0.0 as I'm rethinking the count caches.

**Comment by kirkbushell** [comment]
@cviebrock this has to be tested, sorry but this will need to be closed until such time as we can get them happening.
