### ISSUE TITLE
Correct field types for pivot tables

### ISSUE THREAD

**Issue by canfiax** [kirkbushell/eloquence#48]
What is the correct formatting for pivot tables? Usually, with normal integer ID's it would generate:

        Schema::create('domain_user', function (Blueprint $table) {
            $table->integer('domain_id')->unsigned()->index();
            $table->foreign('domain_id')->references('id')->on('domains')->onDelete('cascade');
            $table->integer('user_id')->unsigned()->index();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->primary(['domain_id', 'user_id']);
        });

I'm thinking below should be enough (simply changing to string 36 and removing unsigned):

        Schema::create('domain_user', function (Blueprint $table) {
            $table->string('domain_id',36)->index();
            $table->foreign('domain_id')->references('id')->on('domains')->onDelete('cascade');
            $table->string('user_id',36)()->index();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->primary(['domain_id', 'user_id']);
        });

But that generates the following error:

    SQLSTATE[HY000]: General error: 1215 Cannot add foreign key const
    raint (SQL: alter table `domain_user` add constraint domain_user_
    domain_id_foreign foreign key (`domain_id`) references `domains`
    (`id`) on delete cascade)

**Comment by kirkbushell** [comment]
Issues should be directly related to any problems that arise within the library, not general questions regarding SQL migrations. I'd recommend reading up SQL table schemas regarding UUIDs.

**Comment by canfiax** [comment]
True, but what about adding this basic information to the documentation?

**Comment by kirkbushell** [comment]
There's plenty of information about how to best store UUIDs on the various SQL platforms :)

**Comment by canfiax** [comment]
Sure. But why not include the basiscs in the documentation?

**Comment by kirkbushell** [comment]
Should I also include documentation on how to write PHP?

Documentation is there for the library, nothing more. You're expected to know certain things if you want to use some of its features.
