### ISSUE TITLE
Unique slugs ?

### ISSUE THREAD

**Issue by DarKDinDoN** [kirkbushell/eloquence#50]
Hello,

Can this package generate unique slugs ?

Thx.

**Comment by kirkbushell** [comment]
It doesn't do checks on slugs, so there is a chance that it could create an erroneous slug. It depends also on the strategy you use. For example if you want to base it off a post title or something, you should be doing that check yourself, and ensuring you have a good strategy for managing it.

**Comment by DarKDinDoN** [comment]
Thx
