### ISSUE TITLE
"Integrity constraint violation: 1062 Duplicate entry" if generated slug is not unique

### ISSUE THREAD

**Issue by oschettler** [kirkbushell/eloquence#54]
The $attempts variable in generateTitleSlug() is not appended properly to the $titleSlug.

I avoid duplicate slugs by having a loop in my application code:

```
// Loop until a unique slug could be generated
$saved = false;
do {
    try {
        $saved = $user->save();
    }
    catch (\Illuminate\Database\QueryException $e);
}
while (!$saved);
```

This loop never finishes.

**Comment by kirkbushell** [comment]
@oschettler - do you plan on doing a PR for this by any chance?

**Comment by kirkbushell** [comment]
@oschettler ?
