### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by msiemens** [kirkbushell/eloquence#75]
Laravel 7 has been released on March 3rd, 2020, it would be lovely to be able to use eloquence with the new version 🙃

**Comment by kirkbushell** [comment]
Open up a PR :) I have very little time for Eloquence these days as I'm just flat-chat with a number of projects so only really update when I need to.

If you can submit a PR it makes it much easier for me to pull, test, and then tag once done.

**Comment by msiemens** [comment]
Will do! Is there anything to keep in mind for the PR?

**Comment by kirkbushell** [comment]
@msiemens the tests - just ensuring things aren't broken :)
