### ISSUE TITLE
Should package discovery be used?

### ISSUE THREAD

**Issue by JayyWalker** [kirkbushell/eloquence#90]
I've noticed the documentation mentions to add `\Eloquence\EloquenceServiceProvider` to `config/app.php`. Most packages use Laravel's automatic package discovery, so it surprised me when this did not show up in the discovered packages list.

Is there a reason why this doesn't use that feature? It's a small amount of work to add so I'm happy to do it if need be.

**Comment by kirkbushell** [comment]
@JayyWalker just never got around to it. Happy to merge any PR that supports auto-discovery :)

**Comment by kirkbushell** [comment]
Coming in 11.0.
