### ISSUE TITLE
Can't work with `confirmed` validator

### ISSUE THREAD

**Issue by chantouchsek** [kirkbushell/eloquence#96]
if we are using `confirmed` validator, it will not pass the validation.

**Comment by kirkbushell** [comment]
@chantouchsek can you provide more information and details?

**Comment by chantouchsek** [comment]
Ok, if we are using this package into model, and that model need to validate `confirmed`. so the validation will never pass.

**Comment by chantouchsek** [comment]
'password' => ['required', 'min:6', 'max:255', 'confirmed'],

**Comment by kirkbushell** [comment]
@chantouchsek I understand what you meant with the original post, I was just hoping for more clarity around what was happening. Is the validator simply returning false? Any errors?

**Comment by chantouchsek** [comment]
> @chantouchsek I understand what you meant with the original post, I was just hoping for more clarity around what was happening. Is the validator simply returning false? Any errors?
> 

I think basically you can reproduce with above validation context.

**Comment by chantouchsek** [comment]
Is there any fix?

**Comment by chantouchsek** [comment]
Ahh maybe using the `CamelCasing` and with the validation of `confirmed`
