### ISSUE TITLE
can't install the package

### ISSUE THREAD

**Issue by rushi7997** [kirkbushell/eloquence#97]
The Error I am getting is here

> `./composer.json has been updated
> Running composer update kirkbushell/eloquence
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires kirkbushell/eloquence 4.0 -> satisfiable by kirkbushell/eloquence[4.0.0].
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires kirkbushell/eloquence 4.0.0 -> satisfiable by kirkbushell/eloquence[4.0.0].
>     - kirkbushell/eloquence 4.0.0 requires illuminate/database ~7.0 -> found illuminate/database[v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
> 
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> `

to reproduce the error simply install the package using the command  `composer require kirkbushell/eloquence:~4.0`
on a fresh laravel 8 project

**Comment by binotaliu** [comment]
For Laravel 8, install ~8.0 version, not ~4.0.
