### ISSUE TITLE
Laravel Octane

### ISSUE THREAD

**Issue by gajosadrian** [kirkbushell/eloquence#98]
Is this package compatibile with [Laravel Octane](https://laravel.com/docs/master/octane)?

Configuration Repository Injection
https://laravel.com/docs/master/octane#configuration-repository-injection

Managing Memory Leaks
https://laravel.com/docs/master/octane#managing-memory-leaks

**Comment by kirkbushell** [comment]
@gajosadrian I can't see why it wouldn't be.

**Comment by gajosadrian** [comment]
Why not? It's very good

**Comment by kirkbushell** [comment]
> Why not? It's very good

Think you misunderstood my response - there's no reason why Eloquence wouldn't work with Octane enabled.
